### ISSUE TITLE
Display corruption 

### ISSUE THREAD

**Issue by sbts** [Kunsi/Octoprint-LCD-HD44780#3]
The current implementation doesn't include any refresh mechanism. 
This allows the display to become corrupted over time if there is noise present on the power supply or any data/control lines.

Implementation of a refresh routine that completes a refresh once every few minutes should minimise the effects of any noise.

This can either be done as a full display write every "refresh seconds" or alternatively as more frequent single character writes

**Comment by Kunsi** [comment]
Should be fixed in 5fcf419

**Comment by Kunsi** [comment]
Actually more like „fixed in 4dbc988“.
